import {
  activateLicense,
  archiveCustomer,
  cancelSubscription,
  createCheckout,
  createCustomer,
  createDiscount,
  createUsageRecord,
  createWebhook,
  deactivateLicense,
  deleteDiscount,
  deleteWebhook,
  generateOrderInvoice,
  generateSubscriptionInvoice,
  getAuthenticatedUser,
  getCheckout,
  getCustomer,
  getDiscount,
  getDiscountRedemption,
  getFile,
  getLicenseKey,
  getLicenseKeyInstance,
  getOrder,
  getOrderItem,
  getPrice,
  getProduct,
  getStore,
  getSubscription,
  getSubscriptionInvoice,
  getSubscriptionItem,
  getSubscriptionItemCurrentUsage,
  getUsageRecord,
  getVariant,
  getWebhook,
  issueOrderRefund,
  issueSubscriptionInvoiceRefund,
  lemonSqueezySetup,
  listCheckouts,
  listCustomers,
  listDiscountRedemptions,
  listDiscounts,
  listFiles,
  listLicenseKeyInstances,
  listLicenseKeys,
  listOrderItems,
  listOrders,
  listPrices,
  listProducts,
  listStores,
  listSubscriptionInvoices,
  listSubscriptionItems,
  listSubscriptions,
  listUsageRecords,
  listVariants,
  listWebhooks,
  updateCustomer,
  updateLicenseKey,
  updateSubscription,
  updateSubscriptionItem,
  updateWebhook,
  validateLicense,
} from "@terminalzero/lemonsqueezy";

lemonSqueezySetup({ apiKey: "v4-migration-fixture" });

const calls = [
  getAuthenticatedUser(),
  getStore(1),
  listStores(),
  createCustomer(1, { name: "Ada", email: "ada@example.com" }),
  updateCustomer(1, { name: "Grace" }),
  archiveCustomer(1),
  getCustomer(1),
  listCustomers(),
  getProduct(1),
  listProducts(),
  getVariant(1),
  listVariants(),
  getPrice(1),
  listPrices(),
  getFile(1),
  listFiles(),
  getOrder(1),
  listOrders(),
  generateOrderInvoice(1),
  issueOrderRefund(1),
  getOrderItem(1),
  listOrderItems(),
  getSubscription(1),
  listSubscriptions(),
  updateSubscription(1, { cancelled: false }),
  cancelSubscription(1),
  getSubscriptionInvoice(1),
  listSubscriptionInvoices(),
  generateSubscriptionInvoice(1),
  issueSubscriptionInvoiceRefund(1),
  getSubscriptionItem(1),
  listSubscriptionItems(),
  getSubscriptionItemCurrentUsage(1),
  updateSubscriptionItem(1, 3),
  createUsageRecord({ subscriptionItemId: 1, quantity: 3 }),
  getUsageRecord(1),
  listUsageRecords(),
  createDiscount({
    storeId: 1,
    name: "Ten percent",
    amount: 10,
    amountType: "percent",
  }),
  getDiscount(1),
  listDiscounts(),
  deleteDiscount(1),
  getDiscountRedemption(1),
  listDiscountRedemptions(),
  getLicenseKey(1),
  listLicenseKeys(),
  updateLicenseKey(1, { disabled: false }),
  getLicenseKeyInstance(1),
  listLicenseKeyInstances(),
  createCheckout(1, 2),
  getCheckout(1),
  listCheckouts(),
  createWebhook(1, {
    url: "https://example.com/webhooks",
    events: ["order_created"],
    secret: "fixture-secret",
  }),
  getWebhook(1),
  updateWebhook(1, { events: ["customer_updated"] }),
  deleteWebhook(1),
  listWebhooks(),
  activateLicense("fixture-license-key", "Fixture instance"),
  validateLicense("fixture-license-key"),
  deactivateLicense("fixture-license-key", "fixture-instance"),
] as const;

const allResourceCallsArePromises: readonly Promise<unknown>[] = calls;
const resourceCallCount: 59 = calls.length;
void allResourceCallsArePromises;
void resourceCallCount;

// Corrected v4 declaration conflicts remain source-compatible.
generateOrderInvoice(1);
generateSubscriptionInvoice(1);
updateSubscriptionItem(1, 3);
updateSubscriptionItem(1, {
  quantity: 3,
  invoiceImmediately: false,
  disableProrations: false,
});

// @ts-expect-error The upstream package name is outside the migration boundary.
import("@lemonsqueezy/lemonsqueezy.js");
// @ts-expect-error Package resource deep imports are closed.
import("@terminalzero/lemonsqueezy/customers");
