#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
TOTAL_MINUTES=15

REPOSITORY="terminalzero-dev/lemonsqueezy.js"
PACKAGE_NAME="@terminalzero/lemonsqueezy"
RELEASE_ISSUE_NUMBER="${RELEASE_ISSUE_NUMBER:-}"
REGISTRY_URL="https://registry.npmjs.org/"
WIZARD_TEMP=$(mktemp -d)
LOGGED_IN=false
NPM_CONFIG_USERCONFIG="$WIZARD_TEMP/npmrc"
export NPM_CONFIG_USERCONFIG
touch "$NPM_CONFIG_USERCONFIG"
chmod 600 "$NPM_CONFIG_USERCONFIG"

cleanup() {
  if [[ "$LOGGED_IN" == "true" ]]; then
    npm logout --registry="$REGISTRY_URL" >/dev/null 2>&1 || true
  fi
  rm -rf "$WIZARD_TEMP"
}
trap cleanup EXIT

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"
# shellcheck source=scripts/lib/retry-command.sh
source "$ROOT/scripts/lib/retry-command.sh"
EVIDENCE_DIRECTORY="$ROOT/.artifacts/manual-dist-tag"
EVIDENCE_PATH="$EVIDENCE_DIRECTORY/dist-tag-interactive-evidence.json"
RESUME_EVIDENCE_PATH=""
TAG_READ_ATTEMPTS=30
TAG_READ_DELAY_SECONDS=3

download_run_artifact() {
  local run_id=$1
  local artifact_name=$2
  local destination=$3

  rm -rf "$destination"
  gh run download "$run_id" -R "$REPOSITORY" \
    --name "$artifact_name" --dir "$destination"
}

wait_for_public_tags() {
  local expected_beta=$1
  local expected_latest=$2
  local attempt

  for ((attempt = 1; attempt <= TAG_READ_ATTEMPTS; attempt += 1)); do
    if ! TAGS=$(retry_command 3 npm view \
      "$PACKAGE_NAME" dist-tags --json --prefer-online --registry="$REGISTRY_URL"); then
      return 1
    fi
    LIVE_BETA=$(jq -r .beta <<<"$TAGS")
    LIVE_LATEST=$(jq -r .latest <<<"$TAGS")
    if [[ "$LIVE_BETA" == "$expected_beta" && \
      "$LIVE_LATEST" == "$expected_latest" ]]; then
      return 0
    fi
    if ((attempt < TAG_READ_ATTEMPTS)); then
      note "Waiting for public npm dist-tags to converge ($attempt/$TAG_READ_ATTEMPTS; beta=$LIVE_BETA, latest=$LIVE_LATEST)..."
      sleep "$TAG_READ_DELAY_SECONDS"
    fi
  done
  return 1
}

banner "v5 beta interactive dist-tag drill"

stage "Verify the published Candidate" 2
say "This reads public npm and GitHub state. It does not mutate the registry."
for command in gh npm node jq git; do
  command -v "$command" >/dev/null 2>&1 || {
    warn "missing required command: $command"
    exit 1
  }
done
retry_command 3 gh auth status >/dev/null
if [[ -n "${NPM_TOKEN:-}" || -n "${NODE_AUTH_TOKEN:-}" ]]; then
  warn "Unset NPM_TOKEN and NODE_AUTH_TOKEN before running this wizard."
  exit 1
fi
if [[ -z "${CANDIDATE_RUN_ID:-}" ]]; then
  ask CANDIDATE_RUN_ID "Successful Release Candidate run ID:"
fi
if [[ -z "${REGISTRY_RELEASE_RUN_ID:-}" ]]; then
  ask REGISTRY_RELEASE_RUN_ID "Successful phase-one Registry Release run ID:"
fi
if [[ -z "$RELEASE_ISSUE_NUMBER" ]]; then
  ask RELEASE_ISSUE_NUMBER "Release evidence Issue number:"
fi
[[ "$CANDIDATE_RUN_ID" =~ ^[1-9][0-9]*$ ]] || {
  warn "Candidate run ID must be numeric"
  exit 1
}
[[ "$REGISTRY_RELEASE_RUN_ID" =~ ^[1-9][0-9]*$ ]] || {
  warn "Registry Release run ID must be numeric"
  exit 1
}
[[ "$RELEASE_ISSUE_NUMBER" =~ ^[1-9][0-9]*$ ]] || {
  warn "Release evidence Issue number must be numeric"
  exit 1
}
RELEASE_ISSUE=$(retry_command 3 gh api \
  "repos/$REPOSITORY/issues/$RELEASE_ISSUE_NUMBER")
[[ "$(jq -r .state <<<"$RELEASE_ISSUE")" == "open" ]]
[[ "$(jq -r '.pull_request // empty' <<<"$RELEASE_ISSUE")" == "" ]]
[[ "$(jq -r .parent_issue_url <<<"$RELEASE_ISSUE")" == \
  "https://api.github.com/repos/$REPOSITORY/issues/39" ]]
RUN=$(retry_command 3 gh api \
  "repos/$REPOSITORY/actions/runs/$CANDIDATE_RUN_ID")
[[ "$(jq -r .name <<<"$RUN")" == "Release Candidate" ]]
[[ "$(jq -r .conclusion <<<"$RUN")" == "success" ]]
RUN_COMMIT=$(jq -r .head_sha <<<"$RUN")
ARTIFACTS=$(retry_command 3 gh api \
  "repos/$REPOSITORY/actions/runs/$CANDIDATE_RUN_ID/artifacts")
MATCHING_ARTIFACTS=$(jq -c \
  --arg commit "$RUN_COMMIT" \
  '[.artifacts[] | select(.name | test("^release-candidate-5\\.0\\.0-beta\\.[1-9][0-9]*-" + $commit + "$")) | .name]' \
  <<<"$ARTIFACTS")
[[ "$(jq -r length <<<"$MATCHING_ARTIFACTS")" -eq 1 ]]
ARTIFACT_NAME=$(jq -r '.[0]' <<<"$MATCHING_ARTIFACTS")
CANDIDATE_DIR="$WIZARD_TEMP/candidate"
retry_command 3 download_run_artifact \
  "$CANDIDATE_RUN_ID" "$ARTIFACT_NAME" "$CANDIDATE_DIR"
CURRENT_VERSION=$(jq -r .version "$CANDIDATE_DIR/candidate.json")
SOURCE_COMMIT=$(jq -r .sourceCommit "$CANDIDATE_DIR/candidate.json")
ARTIFACT_SHA256=$(jq -r .artifact.sha256 "$CANDIDATE_DIR/candidate.json")
EXPECTED_ARTIFACT_NAME="release-candidate-$CURRENT_VERSION-$RUN_COMMIT"
[[ "$ARTIFACT_NAME" == "$EXPECTED_ARTIFACT_NAME" ]]
[[ "$(jq -r .head_sha <<<"$RUN")" == "$SOURCE_COMMIT" ]]
[[ "$CURRENT_VERSION" =~ ^5\.0\.0-beta\.[1-9][0-9]*$ ]]
retry_command 3 git fetch origin release/v5-beta
git merge-base --is-ancestor "$SOURCE_COMMIT" origin/release/v5-beta || {
  warn "Candidate commit is not part of the current release branch"
  exit 1
}
REGISTRY_RUN=$(retry_command 3 gh api \
  "repos/$REPOSITORY/actions/runs/$REGISTRY_RELEASE_RUN_ID")
[[ "$(jq -r .name <<<"$REGISTRY_RUN")" == "Registry Release" ]]
[[ "$(jq -r .conclusion <<<"$REGISTRY_RUN")" == "success" ]]
REGISTRY_RUN_COMMIT=$(jq -r .head_sha <<<"$REGISTRY_RUN")
git merge-base --is-ancestor "$SOURCE_COMMIT" "$REGISTRY_RUN_COMMIT" || {
  warn "Registry Release dispatch commit does not contain the Candidate commit"
  exit 1
}
VERIFIED_ARTIFACT_NAME="registry-release-verified-$CURRENT_VERSION-$ARTIFACT_SHA256"
VERIFIED_ARTIFACT=$(retry_command 3 gh api \
  "repos/$REPOSITORY/actions/runs/$REGISTRY_RELEASE_RUN_ID/artifacts" \
  --jq ".artifacts[] | select(.name == \"$VERIFIED_ARTIFACT_NAME\") | .name")
[[ "$VERIFIED_ARTIFACT" == "$VERIFIED_ARTIFACT_NAME" ]]
REGISTRY_EVIDENCE_DIR="$WIZARD_TEMP/registry-evidence"
retry_command 3 download_run_artifact \
  "$REGISTRY_RELEASE_RUN_ID" "$VERIFIED_ARTIFACT_NAME" "$REGISTRY_EVIDENCE_DIR"
REGISTRY_EVIDENCE="$REGISTRY_EVIDENCE_DIR/registry-evidence.json"
LAST_KNOWN_GOOD_VERSION=$(jq -r .registry.distTags.latest "$REGISTRY_EVIDENCE")
[[ "$LAST_KNOWN_GOOD_VERSION" =~ ^5\.0\.0-beta\.[1-9][0-9]*$ ]]
[[ "$LAST_KNOWN_GOOD_VERSION" != "$CURRENT_VERSION" ]]
[[ "$(jq -r .version "$REGISTRY_EVIDENCE")" == "$CURRENT_VERSION" ]]
[[ "$(jq -r .sourceCommit "$REGISTRY_EVIDENCE")" == "$SOURCE_COMMIT" ]]
[[ "$(jq -r .candidate.runId "$REGISTRY_EVIDENCE")" == "$CANDIDATE_RUN_ID" ]]
[[ "$(jq -r .candidate.artifact.sha256 "$REGISTRY_EVIDENCE")" == "$ARTIFACT_SHA256" ]]
[[ "$(jq -r .registry.provenance.verified "$REGISTRY_EVIDENCE")" == "true" ]]
[[ "$(jq -r .registry.distTags.beta "$REGISTRY_EVIDENCE")" == "$CURRENT_VERSION" ]]
[[ "$(jq -r .registry.distTags.latest "$REGISTRY_EVIDENCE")" == "$LAST_KNOWN_GOOD_VERSION" ]]
HAS_RESUMABLE_EVIDENCE=false
if [[ -f "$EVIDENCE_PATH" && \
  "$(jq -r '.status // empty' "$EVIDENCE_PATH")" == "failed" ]]; then
  jq -e \
    --arg package "$PACKAGE_NAME" \
    --arg current "$CURRENT_VERSION" \
    --arg lkg "$LAST_KNOWN_GOOD_VERSION" \
    --arg commit "$SOURCE_COMMIT" \
    --arg sha256 "$ARTIFACT_SHA256" \
    --arg runId "$REGISTRY_RELEASE_RUN_ID" \
    '.schemaVersion == 1 and
      .status == "failed" and
      .package == $package and
      .currentVersion == $current and
      .lastKnownGoodVersion == $lkg and
      .sourceCommit == $commit and
      .artifactSha256 == $sha256 and
      .registryReleaseRunId == $runId and
      .states[0] == {
        phase: "published", beta: $current, latest: $lkg,
        at: .states[0].at
      } and
      .timeline[0] == {
        tag: "latest", version: $current, at: .timeline[0].at
  }' "$EVIDENCE_PATH" >/dev/null || {
    warn "Existing failed evidence cannot resume this Candidate."
    exit 1
  }
  HAS_RESUMABLE_EVIDENCE=true
fi
if [[ "$HAS_RESUMABLE_EVIDENCE" == "true" ]]; then
  wait_for_public_tags "$CURRENT_VERSION" "$CURRENT_VERSION" || {
    warn "Public dist-tags did not converge to the safely resumable state."
    exit 1
  }
  RESUME_EVIDENCE_PATH="$EVIDENCE_PATH"
  note "The failed promotion is recorded; the drill will resume at rollback."
else
  wait_for_public_tags "$CURRENT_VERSION" "$LAST_KNOWN_GOOD_VERSION" || {
    warn "Public dist-tags did not converge to the verified published state."
    exit 1
  }
  note "The drill will start from the verified published state."
fi
say "Verified $PACKAGE_NAME@$CURRENT_VERSION."
note "Candidate: $SOURCE_COMMIT · SHA-256 $ARTIFACT_SHA256"

stage "Sign in to npm with web authentication" 2
say "npm Trusted Publishing cannot change dist-tags. This stage opens npm's interactive web login."
warn "Do not paste a password, token, OTP, Passkey, or recovery code into this wizard."
npm logout --registry="$REGISTRY_URL" >/dev/null 2>&1 || true
npm login --auth-type=web --registry="$REGISTRY_URL"
LOGGED_IN=true
NPM_ACCOUNT=$(retry_command 3 npm whoami --registry="$REGISTRY_URL")
say "Signed in as npm account: $NPM_ACCOUNT"

stage "Confirm account recovery availability" 1
say "Confirm only that the maintainer account can be recovered."
warn "Do not display or record any recovery material."
confirm "Are account recovery materials available right now?" || {
  warn "Recovery confirmation is required before registry mutation."
  exit 1
}

stage "Promote, rollback, and restore dist-tags" 8
DRILL_COMMAND=(
  node scripts/exercise-dist-tags.mjs
  --package "$PACKAGE_NAME"
  --current-version "$CURRENT_VERSION"
  --last-known-good-version "$LAST_KNOWN_GOOD_VERSION"
  --source-commit "$SOURCE_COMMIT"
  --artifact-sha256 "$ARTIFACT_SHA256"
  --registry-release-run-id "$REGISTRY_RELEASE_RUN_ID"
  --npm-actor "$NPM_ACCOUNT"
  --account-recovery-confirmed
  --registry "$REGISTRY_URL"
  --npm-userconfig "$NPM_CONFIG_USERCONFIG"
)
if [[ -n "$RESUME_EVIDENCE_PATH" ]]; then
  say "The recorded promotion is complete. The drill will roll latest and beta back to $LAST_KNOWN_GOOD_VERSION, then restore both to $CURRENT_VERSION."
  warn "This resume changes public npm resolution four times in a controlled window."
  DRILL_COMMAND+=(--resume-evidence "$RESUME_EVIDENCE_PATH")
else
  say "The drill will move latest to $CURRENT_VERSION, move latest and beta back to $LAST_KNOWN_GOOD_VERSION, then restore both to $CURRENT_VERSION."
  warn "This changes public npm resolution five times in a controlled window."
fi
confirm "Run the public dist-tag drill now?" || exit 1
mkdir -p "$EVIDENCE_DIRECTORY"
DRILL_COMMAND+=(--evidence "$EVIDENCE_PATH")
"${DRILL_COMMAND[@]}"

stage "End the npm session" 1
npm logout --registry="$REGISTRY_URL"
LOGGED_IN=false
say "The interactive npm session is closed."
wait_for_public_tags "$CURRENT_VERSION" "$CURRENT_VERSION" || {
  warn "Public dist-tags did not converge after the npm session closed."
  exit 1
}

stage "Publish evidence and resume finalization" 1
BODY_PATH="$WIZARD_TEMP/issue-comment.md"
{
  printf '%s\n\n' "Interactive npm 2FA dist-tag drill completed."
  printf '\x60\x60\x60json\n'
  cat "$EVIDENCE_PATH"
  printf '\x60\x60\x60\n'
  shopt -s nullglob
  FAILED_EVIDENCE_PATHS=(
    "$EVIDENCE_DIRECTORY"/dist-tag-interactive-failed-"$REGISTRY_RELEASE_RUN_ID"-*.json
  )
  shopt -u nullglob
  for failed_evidence_path in "${FAILED_EVIDENCE_PATHS[@]}"; do
    node scripts/validate-failed-dist-tag-evidence.mjs \
      --evidence "$failed_evidence_path" \
      --package "$PACKAGE_NAME" \
      --current-version "$CURRENT_VERSION" \
      --last-known-good-version "$LAST_KNOWN_GOOD_VERSION" \
      --source-commit "$SOURCE_COMMIT" \
      --artifact-sha256 "$ARTIFACT_SHA256" \
      --registry-release-run-id "$REGISTRY_RELEASE_RUN_ID" \
      --npm-actor "$NPM_ACCOUNT" >/dev/null || {
      warn "Refusing to publish invalid failed evidence: $failed_evidence_path"
      exit 1
    }
    printf '\n%s\n\n' "Prior failed attempt retained for recovery audit: $(basename "$failed_evidence_path")"
    printf '\x60\x60\x60json\n'
    cat "$failed_evidence_path"
    printf '\x60\x60\x60\n'
  done
} > "$BODY_PATH"
say "The complete Issue comment below is secret-free evidence. Review it before posting."
cat "$BODY_PATH"
confirm "Post this complete evidence chain to Issue #$RELEASE_ISSUE_NUMBER?" || exit 1
COMMENT=$(jq -Rs '{body: .}' < "$BODY_PATH" | \
  gh api "repos/$REPOSITORY/issues/$RELEASE_ISSUE_NUMBER/comments" --method POST --input -)
COMMENT_ID=$(jq -r .id <<<"$COMMENT")
COMMENT_URL=$(jq -r .html_url <<<"$COMMENT")
say "Evidence comment: $COMMENT_URL"
confirm "Dispatch the evidence-verifying finalization run now?" || {
  note "Resume later with dist_tag_evidence_comment_id=$COMMENT_ID"
  exit 0
}
gh workflow run registry-release.yml -R "$REPOSITORY" \
  --ref release/v5-beta \
  -f candidate_run_id="$CANDIDATE_RUN_ID" \
  -f expected_version="$CURRENT_VERSION" \
  -f expected_commit="$SOURCE_COMMIT" \
  -f expected_sha256="$ARTIFACT_SHA256" \
  -f last_known_good_version="$LAST_KNOWN_GOOD_VERSION" \
  -f dist_tag_evidence_issue_number="$RELEASE_ISSUE_NUMBER" \
  -f resume_published=true \
  -f dist_tag_evidence_comment_id="$COMMENT_ID"
say "Finalization dispatched. It will revalidate the comment, live tags, package bytes, and provenance."

finish
